# Generated by Django 5.2.4 on 2025-07-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='autorUser',
            new_name='authorUser',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='ratingAutor',
            new_name='ratingAuthor',
        ),
    ]
