# Generated by Django 5.2.4 on 2025-10-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client_name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='message',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='time_creation',
        ),
    ]
